/**
 * Per-content-type configuration for UserContentCommonOptions.
 */
export const USER_CONTENT_OPTIONS_CONFIG = {
  text_input: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: true,
    apiValidation: true,
    requireInline: true,
    displayContinueButton: false,
    apiSelect: {
      valueField: 'data_use_api_input_value',
      changeField: 'data_use_api_input_value',
      dataSource: 'empty',
      keyValue: 'key',
    },
  },
  image: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: true,
    saveToVariable: true,
    apiValidation: true,
    requireInline: false,
    displayContinueButton: true,
    apiSelect: {
      valueField: 'use_api_input_value',
      changeField: 'use_api_input_value',
      dataSource: 'variables',
      keyValue: 'variable_name',
      nameValue: 'variable_name',
    },
  },
  textarea: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: true,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  pull_down: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: true,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
    requireStandalone: true,
  },
  checkbox: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: true,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
    requireStandalone: true,
  },
  radio_button: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: true,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
    requireStandalone: true,
  },
  calendar: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  card_payment_radio_button: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  shipping_address: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  credit_card_payment: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  product_purchase: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  product_purchase_radio_button: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  product_purchase_select_option: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  slider: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: true,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  zip_code_address: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  attaching_file: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  agree_term: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  carousel: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  capture: {
    hideWhenLoggedIn: false,
    hideWhenError: false,
    faq: false,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  sms_verify: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  AFTEE_payment_module: {
    hideWhenLoggedIn: false,
    hideWhenError: false,
    faq: false,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  button_submit: {
    hideWhenLoggedIn: true,
    hideWhenError: true,
    faq: true,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  label: {
    hideWhenLoggedIn: false,
    hideWhenError: false,
    faq: false,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
  label_no_transition: {
    hideWhenLoggedIn: false,
    hideWhenError: false,
    faq: false,
    noAutoScroll: false,
    saveToVariable: false,
    apiValidation: false,
    requireInline: false,
    displayContinueButton: false,
  },
};

export const getUserContentOptionsConfig = (contentType) =>
  USER_CONTENT_OPTIONS_CONFIG[contentType] || null;
