export const SCENARIO_MODAL_TOOLTIPS = {
  lpProductUrl: '商品購入ページのURLを入力してください。',
  urlThanks: '購入完了後のサンクスページのURLを入力してください。',
  merchandiseId: 'Shopifyの商品IDまたはバリアントIDを入力してください。',
  productIdCrossSell: 'クロスセル用の商品IDまたはバリアントIDを入力してください。',
  coupon: '適用するクーポンコードを入力してください。',
  launchButtonSelectors: '複数セレクターはカンマ区切り。クリックでチャットボットを開きます。',
  isUseCustomCss: 'カスタムCSSをチャットボットに適用します。',
  isUseCustomJsCode: 'カスタムJSコードをチャットボットに適用します。',
  timer: 'チャットボット内にカウントダウンタイマーを表示します。',
  isUseErrMsgByJs: 'フォームのエラーメッセージをJSまたはセレクターで取得します。',
  isUseOnlyRegularOrder: '定期注文のみを対象とします。',
  isUseFukushashiki: '複写式チャットボット機能を有効にします。',
  isUseAmazonPay: 'Amazon Pay連携を有効にします。LP連携モードや許可ドメインを設定できます。',
  amazonPayLpIntegrationMode: 'Amazon Pay連携時のLP判定方式を選択します。Genericは許可ドメイン設定に基づき、Legacyは既存のドメイン判定ロジックを使用します。AutoはGenericを優先し、利用できない場合はLegacyに切り替えます。',
  amazonPayAllowedLpDomains: 'Amazon Pay連携を許可するLPのドメインを1行に1件ずつ入力してください。プロトコル（https://）やパスは不要です。',
  amazonPayPollInterval: 'LPページでAmazon Payの読み込み完了を確認する際の、ポーリング間隔（ミリ秒）です。',
  amazonPayMaxPollCount: 'Amazon Payの読み込み完了を確認する最大ポーリング回数です。この回数に達しても完了しない場合は処理を中断します。',
  isUsedMessageLoadedPast: '過去のメッセージ履歴を読み込みます。',
  useFullwidthChatbotMobile: 'モバイル端末でチャットボットを全画面表示します。',
  isUsedCrosssell: 'クロスセル商品をカートに自動追加します。',
  isClearLandingPageSession: 'ページ読み込み時に自動ログアウト処理を実行します。',
  isUseBtnUpdateTracking: '「登録」ボタンの変更を有効化する',
  cssContent: 'ここにカスタムCSSコンテンツを入力してください。',
  headJsContent: 'HTMLのheadタグ内に挿入するJSコードを入力してください。',
  topBodyJsContent: 'bodyタグ上部に挿入するJSコードを入力してください。',
  bottomBodyJsContent: 'bodyタグ下部に挿入するJSコードを入力してください。',
  timerDuration: 'タイマーのカウントダウン時間を設定します。',
  timerCountingMessage: 'カウント中に表示するメッセージを入力してください。',
  timerFinishMessage: 'タイマー終了時に表示するメッセージを入力してください。',
  isUseGlobalDelay: 'すべてのボットメッセージ表示前に待ち時間を設けます。',
  globalDelayTime: 'ボットメッセージが表示されるまでの待ち時間（秒）を設定します。',
  errMsgJsCode: 'エラーメッセージを取得するJSコードを入力してください。',
  errMsgFieldSelectors: 'フィールドエラーを取得するCSSセレクター（カンマ区切り）。',
  errMsgFormSelectors: 'フォームエラーを取得するCSSセレクター（カンマ区切り）。',
  autoLogoutLpUrl: 'ランディングページのURLを入力してください。',
  autoLogoutSignoutUrl: 'ログアウト処理を行うURLを入力してください。',
  variableName: 'シナリオ内で使用する変数名を入力してください。',
  variableDefault: '変数のデフォルト値を入力してください。',
  shopifyVariant: '参照するShopify商品バリアントを選択してください。',
  alignBeginningStop: 'このメッセージを表示したとき、チャットの先頭位置でスクロールを止めます。',
  notUseButton: '登録ボタンをチャット画面に表示しません。',
  registerButtonName: 'ユーザーに表示するボタンの文言を入力します。（例：次へ、登録する）',
  useButtonJavascript: 'ボタンをクリックしたときに、下記のJavaScriptを実行します。',
  registerButtonJscode: 'ボタンクリック時に実行するコードを入力してください。',
  hideWhenLoggedIn: 'ログイン済みユーザーにはこのメッセージを表示しません。',
  hideWhenError: 'エラー発生時にはこのメッセージを表示しません。',
  noAutoScroll: 'このメッセージ表示時に自動スクロールしません。',
  saveToVariable: 'ユーザーの入力を指定した変数に保存します。',
  apiValidation: '入力値の検証にAPIを利用します。',
  displayContinueButton: 'チャット内に「続行」ボタンを表示します。',
  require: 'この入力を必須にします。',
};

export const REGISTER_BUTTON_LABELS = {
  alignBeginningStop: '先頭でスクロールを止める',
  notUseButton: '登録ボタンを表示しない',
  registerButtonName: 'ボタンの表示名',
  useButtonJavascript: 'JavaScriptを実行する',
  registerButtonJscode: 'JavaScriptコード',
};

export const USER_CONTENT_OPTION_LABELS = {
  hideWhenLoggedIn: 'ログイン済みのときは表示しない',
  hideWhenError: 'エラー時は表示しない',
  noAutoScroll: '自動でスクロールしない',
  saveToVariable: '入力内容を変数に保存する',
  apiValidation: '入力値をAPIで検証する',
  displayContinueButton: '「続行」ボタンを表示する',
  require: '必須',
};

export const SETTINGS_MODAL_VIEWS = {
  MAIN: 'main',
  CSS: 'css',
  JS: 'js',
  TIMER: 'timer',
  ERR_MSG: 'errMsg',
  AUTO_LOGOUT: 'autoLogout',
  AMAZON_PAY: 'amazonPay',
  GLOBAL_DELAY: 'globalDelay',
};

export const SETTINGS_VIEW_TITLES = {
  [SETTINGS_MODAL_VIEWS.MAIN]: 'シナリオ設定',
  [SETTINGS_MODAL_VIEWS.CSS]: 'カスタム CSS を入力',
  [SETTINGS_MODAL_VIEWS.JS]: 'カスタムJSコードを入力',
  [SETTINGS_MODAL_VIEWS.TIMER]: 'タイマーを使用する',
  [SETTINGS_MODAL_VIEWS.ERR_MSG]: 'エラーメッセージ取得設定',
  [SETTINGS_MODAL_VIEWS.AUTO_LOGOUT]: '自動ログアウト設定',
  [SETTINGS_MODAL_VIEWS.AMAZON_PAY]: 'Amazon Pay 連携設定',
  [SETTINGS_MODAL_VIEWS.GLOBAL_DELAY]: '表示待ち時間を設定する',
};
