export const CHATBOT_ACTIONS = {
  UPDATE_CREDIT_CARD_FORM: 'updateCreditCardForm',
  CLICK_BUTTON: 'clickButton',
  EXCUTE_JS: 'excuteJS',
  FUKUSHASHIKI: 'fukushashiki',
  GET_ERROR_MESSAGE: 'getErrorMessage',
  GET_ERROR_MESSAGE_WITH_DISPLAY_MSG: 'getErrorMessageWithDisplayMsg',
  CRAWL_DATA: 'crawlData',
  OPEN_PREVIEW: 'openPreview',
  GET_PREVIEW_ORDER_CONTENT: 'getPreviewOrderContent',
  PREVIEW_OBJECT: 'previewObject',
  SET_CHATBOT_CONVERSION_PARAMS_TO_LOCAL_STORAGE: 'setChatbotConversionParamsToLocalStorage',
  INJECT_CUSTOM_JS: 'injectCustomJS',
  UPDATE_AMAZON_PAY_DATA: 'updateAmazonPayData',
  UPDATE_AMAZON_PAY_DATA_FOR_BLISS: 'updateAmazonPayDataForBliss',
  UPDATE_AMAZON_PAY_DATA_FOR_ROSEMAY: 'updateAmazonPayDataForRoseMay',
  UPDATE_AMAZON_PAY_DATA_FOR_PHYSTECH: 'updateAmazonPayDataForPhystech',
  UPDATE_AMAZON_PAY_DATA_FOR_YUWAERU: 'updateAmazonPayDataForYuwaeru',
  UPDATE_AMAZON_PAY_DATA_BY_SELECTOR: 'updateAmazonPayDataBySelector',
  UPDATE_NUMBER_ORDER_TO_UPSELL: 'updateNumberOrderToUpsell',
  LP_FIELD_CHANGED: 'lpFieldChanged',
};
