const PLACEHOLDER = 'この項目の説明は準備中です。';

export const DESIGN_SETTING_TOOLTIPS = {
  title: PLACEHOLDER,
  subtitle: PLACEHOLDER,
  designType: PLACEHOLDER,
  messageIcon: PLACEHOLDER,
  openingIcon: PLACEHOLDER,
  closingIcon: PLACEHOLDER,
  botName: PLACEHOLDER,
  mainColor: PLACEHOLDER,
  displayType: PLACEHOLDER,
  size: PLACEHOLDER,
  position: PLACEHOLDER,
  buttonType: PLACEHOLDER,
  rightTitle: PLACEHOLDER,
  rightMargin: PLACEHOLDER,
  bottomMargin: PLACEHOLDER,
  titleBubble: PLACEHOLDER,
  popupCloseBot: PLACEHOLDER,
  headerTextColor: PLACEHOLDER,
  progressBarBgColor: PLACEHOLDER,
  progressBarTextColor: PLACEHOLDER,
  chatWindowBgColor: PLACEHOLDER,
  botMessageBgColor: PLACEHOLDER,
  botMessageTextColor: PLACEHOLDER,
  userMessageBgColor: PLACEHOLDER,
  userMessageTextColor: PLACEHOLDER,
  fieldFocusBorderColor: PLACEHOLDER,
  fieldFocusBgColor: PLACEHOLDER,
  fieldFocusBgEffect: PLACEHOLDER,
  fieldUnfocusBorderColor: PLACEHOLDER,
  fieldUnfocusBgColor: PLACEHOLDER,
  buttonNormalBgColor: PLACEHOLDER,
  buttonNormalTextColor: PLACEHOLDER,
  buttonPressedBgColor: PLACEHOLDER,
  buttonPressedTextColor: PLACEHOLDER,
  buttonDisabledBgColor: PLACEHOLDER,
  buttonDisabledTextColor: PLACEHOLDER,
  checkboxUncheckedBgColor: PLACEHOLDER,
  checkboxUncheckedBorderColor: PLACEHOLDER,
  checkboxCheckedBgColor: PLACEHOLDER,
  checkboxCheckedBorderColor: PLACEHOLDER,
  radioUnselectedBgColor: PLACEHOLDER,
  radioSelectedBgColor: PLACEHOLDER,
  radioUnselectedBorderColor: PLACEHOLDER,
  radioSelectedBorderColor: PLACEHOLDER,
  radioInputUnselectedColor: PLACEHOLDER,
  radioInputSelectedColor: PLACEHOLDER,
  errorMessageBgColor: PLACEHOLDER,
  errorMessageTextColor: PLACEHOLDER,
  errorMessageFontSize: PLACEHOLDER,
};

export const getDesignSettingTooltip = (key) => DESIGN_SETTING_TOOLTIPS[key] || '';
