export const DESIGN_SETTING_TOOLTIPS = {
  title: 'この項目の説明は準備中です。',
  subtitle: 'この項目の説明は準備中です。',
  designType: 'この項目の説明は準備中です。',
  messageIcon: 'この項目の説明は準備中です。',
  openingIcon: 'この項目の説明は準備中です。',
  closingIcon: 'この項目の説明は準備中です。',
  botName: 'この項目の説明は準備中です。',
  mainColor: 'ヘッダー背景とプログレスバーの塗りつぶし色です。多くのボタン・フォーカス色の基準にもなります。',
  displayType: 'この項目の説明は準備中です。',
  size: 'この項目の説明は準備中です。',
  position: 'この項目の説明は準備中です。',
  buttonType: 'この項目の説明は準備中です。',
  rightTitle: 'この項目の説明は準備中です。',
  rightMargin: 'この項目の説明は準備中です。',
  bottomMargin: 'この項目の説明は準備中です。',
  titleBubble: 'この項目の説明は準備中です。',
  popupCloseBot: 'この項目の説明は準備中です。',
  headerTitleTextColor: 'ヘッダー内のタイトル（メイン見出し）の文字色です。メインカラーとのコントラストに注意してください。',
  headerTitleFontSize: 'ヘッダー内のタイトルのフォントサイズです。単位は px です。',
  headerSubtitleTextColor: 'ヘッダー内のサブタイトルの文字色です。メインカラーとのコントラストに注意してください。',
  headerSubtitleFontSize: 'ヘッダー内のサブタイトルのフォントサイズです。単位は px です。',
  progressBarBgColor: 'プログレスバーのトラック（未進捗部分）の背景色です。塗りつぶし部分はメインカラーが使われます。',
  progressBarTextColor: 'プログレスバー内の進捗テキスト（例: 1 / 3）の文字色です。',
  progressBarFontSize: 'プログレスバー内の進捗テキストのフォントサイズです。単位は px です。',
  chatWindowBgColor: 'チャットウィンドウ全体の背景色です。プレビューのメッセージエリア背景に反映されます。',
  botMessageBgColor: 'ボット側の吹き出し背景色です。プレビュー左側のメッセージに反映されます。',
  botMessageTextColor: 'ボット側の吹き出し内テキストの文字色です。',
  botMessageFontSize: 'ボット側の吹き出し内テキストのフォントサイズです。単位は px です。',
  botMessageBorderStyle: 'ボット側の吹き出しの枠スタイルです。しっぽありは左下に吹き出しのしっぽが表示されます。',
  userMessageBgColor: 'ユーザー側の吹き出し背景色です。プレビュー右側のメッセージに反映されます。',
  userMessageTextColor: 'ユーザー側の吹き出し内テキストの文字色です。',
  userMessageFontSize: 'ユーザー側の吹き出し内テキストのフォントサイズです。単位は px です。',
  userMessageBorderStyle: 'ユーザー側の吹き出しの枠スタイルです。しっぽありは右下に吹き出しのしっぽが表示されます。',
  fieldFocusBorderColor: '入力欄・プルダウンをタップしたときの枠線色です。通常はメインカラーと揃えると統一感が出ます。',
  fieldFocusBgColor: '入力欄・プルダウンをタップしたときの背景色です。',
  fieldFocusBgEffect: '入力欄をタップしたときの視覚効果です。枠線きらきらはフォーカス時の枠線色で点滅します。プレビューでフォーカス状態の欄を確認できます。',
  fieldUnfocusBorderColor: '入力欄・プルダウンの通常時（非フォーカス）の枠線色です。',
  fieldUnfocusBgColor: '入力欄・プルダウンの通常時（非フォーカス）の背景色です。',
  fieldFontSize: '入力欄・プルダウンのフォントサイズです。単位は px です。',
  validationMessageBgColor: '入力欄のバリデーションメッセージ（例: 入力してください）の背景色です。上部のエラーバナーとは別の設定です。',
  validationMessageTextColor: '入力欄のバリデーションメッセージの文字色です。',
  validationMessageFontSize: '入力欄のバリデーションメッセージのフォントサイズです。単位は px です。',
  requiredLabelTextColor: '必須ラベル（※必須）の文字色です。',
  requiredLabelFontSize: '必須ラベル（※必須）のフォントサイズです。単位は px です。',
  buttonNormalBgColor: 'ボタンの通常時の背景色です。プレビュー「通常」ボタンに反映されます。',
  buttonNormalTextColor: 'ボタンの通常時の文字色です。',
  buttonPressedBgColor: 'ボタンを押下したときの背景色です。プレビュー「押下」ボタンに反映されます。',
  buttonPressedTextColor: 'ボタンを押下したときの文字色です。',
  buttonDisabledBgColor: '無効状態のボタン背景色です。プレビュー「無効」ボタンに反映されます。',
  buttonDisabledTextColor: '無効状態のボタン文字色です。',
  buttonFontSize: 'ボタンのフォントサイズです。単位は px です。',
  buttonBorderStyle: 'ボタンの角の丸みです。角なし・少し丸・ピル型から選べます。',
  buttonEffect: 'ボタンの動きの効果です。動かすを選ぶと上下にバウンスするアニメーションが付きます。',
  buttonWidth: 'ボタンの幅です。単位は % で、親要素に対する割合で指定します。空欄の場合は自動幅になります。',
  buttonPadding: 'ボタン内側の余白です。% または px で指定できます。',
  buttonPosition: 'ボタンの横方向の配置です。次へボタンや送信ボタンの位置に反映されます。',
  checkboxUncheckedBgColor: 'チェックボックス未選択時の背景色です。',
  checkboxUncheckedBorderColor: 'チェックボックス未選択時の枠線色です。',
  checkboxCheckedBgColor: 'チェックボックス選択時の背景色です。通常はメインカラーと揃えると統一感が出ます。',
  checkboxCheckedBorderColor: 'チェックボックス選択時の枠線色です。',
  checkboxCheckedBorderEffect: 'チェックボックス選択時の枠線効果です。枠線きらきらは選択時の枠線色で点滅します。',
  checkboxFontSize: 'チェックボックスのラベル文字のフォントサイズです。単位は px です。',
  radioUnselectedBgColor: 'ラジオボタン（未選択）の背景色です。画像形式・テキスト形式の両方に反映されます。',
  radioSelectedBgColor: 'ラジオボタン（選択時）の背景色です。',
  radioUnselectedBorderColor: 'ラジオボタン（未選択）の枠線色です。',
  radioSelectedBorderColor: 'ラジオボタン（選択時）の枠線色です。',
  radioSelectedBorderEffect: 'ラジオボタン選択時の枠線効果です。枠線きらきらは選択時の枠線色で点滅します。',
  radioInputUnselectedColor: 'テキスト形式ラジオボタンの丸印（未選択時）の色です。',
  radioInputSelectedColor: 'テキスト形式ラジオボタンの丸印（選択時）の色です。通常はメインカラーと揃えると統一感が出ます。',
  radioFontSize: 'ラジオボタンのラベル文字のフォントサイズです。単位は px です。',
  errorMessageBgColor: 'エラーメッセージの背景色です。プレビュー上部のエラーバナーに反映されます。',
  errorMessageTextColor: 'エラーメッセージの文字色です。',
  errorMessageFontSize: 'エラーメッセージのフォントサイズです。単位は px です。',
  modalBgColor: 'モーダルの背景色です。郵便番号検索ポップアップや離脱防止モーダルに反映されます。',
  modalTitleTextColor: 'モーダルタイトルの文字色です。',
  modalTitleFontSize: 'モーダルタイトルのフォントサイズです。単位は px です。',
  modalTitleAlignment: 'モーダルタイトルの横方向の配置です。郵便番号検索ポップアップや離脱防止モーダルに反映されます。',
  modalCancelButtonBgColor: 'モーダルの「チャットに戻る」ボタンの背景色です。離脱防止モーダルに反映されます。',
  modalCancelButtonTextColor: 'モーダルの「チャットに戻る」ボタンの文字色です。',
  modalCancelButtonBorderColor: 'モーダルの「チャットに戻る」ボタンの枠線色です。',
  modalCloseButtonBgColor: 'モーダルの「閉じる」ボタンの背景色です。離脱防止モーダルに反映されます。',
  modalCloseButtonTextColor: 'モーダルの「閉じる」ボタンの文字色です。',
  modalButtonFontSize: 'モーダル内ボタンのフォントサイズです。単位は px です。',
};

export const getDesignSettingTooltip = (key) => DESIGN_SETTING_TOOLTIPS[key] || '';
