export const DESIGN_SETTING_TOOLTIPS = {
  title: 'チャットボットのヘッダーに表示するメインタイトルです。お客様に見える文言です。',
  subtitle: 'チャットボットのヘッダーに表示するサブタイトルです。タイトルの下に小さく表示されます。',
  designType: 'チャットボット全体の見た目スタイルです。ポップ・フラット・マテリアルから選べます。',
  messageIcon: 'ボットメッセージ横に表示するアイコン画像です。未設定の場合はデフォルト画像が使われます。',
  openingIcon: 'チャットが開いているときに表示する起動ボタン（フローティング）のアイコンです。',
  closingIcon: 'チャットが閉じているときに表示する起動ボタン（フローティング）のアイコンです。',
  botName: '管理画面上でボットを識別するための名称です。チャット画面には表示されません。',
  chatBodyVersion: 'ビルド／埋め込み時に使用するチャット本体（SDK）のバージョンです。古いバージョンに変更すると、新しく実装された機能が正しく動作しない可能性があります。',
  mainColor: 'チャットボットのヘッダー背景色です。この色は他のセクション（プログレスバー・メッセージ・ボタンなど）には適用されません。',
  displayType: 'ページ読み込み時のチャット表示方法です。リロードで自動表示、非表示、ボタン押下で開くから選べます。',
  size: 'チャットウィンドウの幅と高さです。PCはpx、スマホは画面に対する割合（%）で指定します。',
  position: '起動ボタンの設置位置です。画面下辺または右辺に配置できます。',
  buttonType: '下辺設置時の起動ボタン表示内容です。ボタンのみ、またはボタンとタイトルの組み合わせから選べます。',
  rightTitle: '右辺設置時に起動ボタン横（または上）に表示するタイトル文言です。',
  rightMargin: '起動ボタンの画面右端からの余白です。単位はピクセル（px）です。',
  bottomMargin: '起動ボタンの画面下端からの余白です。単位はピクセル（px）です。',
  titleBubble: '閉じた状態の起動バブルに表示する短いキャッチコピーです。',
  popupCloseBot: 'チャットを閉じようとしたときに確認モーダルを表示する離脱防止機能のオン／オフです。',
  openAnimationDurationMs: 'チャットウィンドウが開くアニメーションの長さです。単位はミリ秒（ms）で、0〜10000の範囲で指定できます。',
  openAnimationStyle: 'チャットウィンドウが開くときのアニメーションの種類です。スライドアップ・フェードイン・ズームイン・右からスライド・角から拡大するから選べます。',
  headerBgColor: 'チャットボットのヘッダー背景色です。この色は他のセクションには適用されません。',
  headerTitleTextColor: 'ヘッダー内のタイトル（メイン見出し）の文字色です。メインカラーとのコントラストに注意してください。',
  headerTitleFontSize: 'ヘッダー内のタイトルのフォントサイズです。単位は px です。',
  headerSubtitleTextColor: 'ヘッダー内のサブタイトルの文字色です。メインカラーとのコントラストに注意してください。',
  headerSubtitleFontSize: 'ヘッダー内のサブタイトルのフォントサイズです。単位は px です。',
  progressBarBgColor: 'プログレスバーのトラック（未進捗部分）の背景色です。',
  progressBarFillColor: 'プログレスバーの塗りつぶし（進捗部分）の色です。ヘッダー色とは独立しています。',
  progressBarTextColor: 'プログレスバー内の進捗テキスト（例: 1 / 3）の文字色です。',
  progressBarFontSize: 'プログレスバー内の進捗テキストのフォントサイズです。単位は px です。',
  chatWindowBgColor: 'チャットウィンドウ全体の背景色です。プレビューのメッセージエリア背景に反映されます。',
  botMessageBgColor: 'ボット側の吹き出し背景色です。プレビュー左側のメッセージに反映されます。',
  botMessageTextColor: 'ボット側の吹き出し内テキストの文字色です。',
  botMessageFontSize: 'ボット側の吹き出し内テキストのフォントサイズです。単位は px です。',
  botMessageBorderStyle: 'ボット側の吹き出しの枠スタイルです。しっぽありは左下に吹き出しのしっぽが表示されます。',
  userMessageBgColor: 'ユーザー側の吹き出し背景色です。プレビュー右側のメッセージに反映されます。',
  userMessageTextColor: 'ユーザー側の吹き出し内テキストの文字色です。',
  userMessageFontSize: 'ユーザー側の吹き出し内テキストのフォントサイズです。単位は px です。',
  userMessageBorderStyle: 'ユーザー側の吹き出しの枠スタイルです。しっぽありは右下に吹き出しのしっぽが表示されます。',
  fieldFocusBorderColor: '入力欄・プルダウンをタップしたときの枠線色です。通常はメインカラーと揃えると統一感が出ます。',
  fieldFocusBgColor: '入力欄・プルダウンをタップしたときの背景色です。',
  fieldFocusBgEffect: '入力欄をタップしたときの視覚効果です。枠線きらきらはフォーカス時の枠線色で点滅します。プレビューでフォーカス状態の欄を確認できます。',
  fieldUnfocusBorderColor: '入力欄・プルダウンの通常時（非フォーカス）の枠線色です。',
  fieldUnfocusBgColor: '入力欄・プルダウンの通常時（非フォーカス）の背景色です。',
  fieldFontSize: '入力欄・プルダウンのフォントサイズです。単位は px です。',
  validationMessageBgColor: '入力欄のバリデーションメッセージ（例: 入力してください）の背景色です。上部のエラーバナーとは別の設定です。',
  validationMessageTextColor: '入力欄のバリデーションメッセージの文字色です。',
  validationMessageFontSize: '入力欄のバリデーションメッセージのフォントサイズです。単位は px です。',
  requiredLabelTextColor: '必須ラベル（※必須）の文字色です。',
  requiredLabelFontSize: '必須ラベル（※必須）のフォントサイズです。単位は px です。',
  buttonNormalBgColor: 'ボタンの通常時の背景色です。プレビュー「通常」ボタンに反映されます。',
  buttonNormalTextColor: 'ボタンの通常時の文字色です。',
  buttonPressedBgColor: 'ボタンを押下したときの背景色です。プレビュー「押下」ボタンに反映されます。',
  buttonPressedTextColor: 'ボタンを押下したときの文字色です。',
  buttonDisabledBgColor: '無効状態のボタン背景色です。プレビュー「無効」ボタンに反映されます。',
  buttonDisabledTextColor: '無効状態のボタン文字色です。',
  buttonFontSize: 'ボタンのフォントサイズです。単位は px です。',
  buttonBorderStyle: 'ボタンの角の丸みです。角なし・少し丸・ピル型から選べます。',
  buttonEffect: 'ボタンの動きの効果です。動かすを選ぶと上下にバウンスするアニメーションが付きます。',
  buttonWidth: 'ボタンの幅です。単位は % で、親要素に対する割合で指定します。空欄の場合は自動幅になります。',
  buttonPadding: 'ボタン内側の余白です。% または px で指定できます。',
  buttonPosition: 'ボタンの横方向の配置です。次へボタンや送信ボタンの位置に反映されます。',
  checkboxUncheckedBgColor: 'チェックボックス未選択時の背景色です。',
  checkboxUncheckedBorderColor: 'チェックボックス未選択時の枠線色です。',
  checkboxCheckedBgColor: 'チェックボックス選択時の背景色です。通常はメインカラーと揃えると統一感が出ます。',
  checkboxCheckedBorderColor: 'チェックボックス選択時の枠線色です。',
  checkboxCheckedBorderEffect: 'チェックボックス選択時の枠線効果です。枠線きらきらは選択時の枠線色で点滅します。',
  checkboxFontSize: 'チェックボックスのラベル文字のフォントサイズです。単位は px です。',
  radioUnselectedBgColor: 'ラジオボタン（未選択）の背景色です。画像形式・テキスト形式の両方に反映されます。',
  radioSelectedBgColor: 'ラジオボタン（選択時）の背景色です。',
  radioUnselectedBorderColor: 'ラジオボタン（未選択）の枠線色です。',
  radioSelectedBorderColor: 'ラジオボタン（選択時）の枠線色です。',
  radioSelectedBorderEffect: 'ラジオボタン選択時の枠線効果です。枠線きらきらは選択時の枠線色で点滅します。',
  radioInputUnselectedColor: 'テキスト形式ラジオボタンの丸印（未選択時）の色です。',
  radioInputSelectedColor: 'テキスト形式ラジオボタンの丸印（選択時）の色です。通常はメインカラーと揃えると統一感が出ます。',
  radioFontSize: 'ラジオボタンのラベル文字のフォントサイズです。単位は px です。',
  errorMessageBgColor: 'エラーメッセージの背景色です。プレビュー上部のエラーバナーに反映されます。',
  errorMessageTextColor: 'エラーメッセージの文字色です。',
  errorMessageFontSize: 'エラーメッセージのフォントサイズです。単位は px です。',
  modalBgColor: 'モーダルの背景色です。郵便番号検索ポップアップや離脱防止モーダルに反映されます。',
  modalTitleTextColor: 'モーダルタイトルの文字色です。',
  modalTitleFontSize: 'モーダルタイトルのフォントサイズです。単位は px です。',
  modalTitleAlignment: 'モーダルタイトルの横方向の配置です。郵便番号検索ポップアップや離脱防止モーダルに反映されます。',
  modalCancelButtonBgColor: 'モーダルの「チャットに戻る」ボタンの背景色です。離脱防止モーダルに反映されます。',
  modalCancelButtonTextColor: 'モーダルの「チャットに戻る」ボタンの文字色です。',
  modalCancelButtonBorderColor: 'モーダルの「チャットに戻る」ボタンの枠線色です。',
  modalCloseButtonBgColor: 'モーダルの「閉じる」ボタンの背景色です。離脱防止モーダルに反映されます。',
  modalCloseButtonTextColor: 'モーダルの「閉じる」ボタンの文字色です。',
  modalButtonFontSize: 'モーダル内ボタンのフォントサイズです。単位は px です。',
};

export const getDesignSettingTooltip = (key) => DESIGN_SETTING_TOOLTIPS[key] || '';
