import * as esbuild from 'esbuild';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const entryPoint = path.join(rootDir, 'src/v2/sdk/index.js');
const outfile = path.join(rootDir, 'public/v2/sdk.js');
const banner = '// Generated by npm run build:sdk — edit src/v2/sdk/ instead.\n';

const buildOptions = {
  entryPoints: [entryPoint],
  bundle: true,
  format: 'iife',
  target: ['es2015'],
  outfile,
  minify: false,
  banner: { js: banner },
  logLevel: 'info',
};

const isWatch = process.argv.includes('--watch');

async function build() {
  await mkdir(path.dirname(outfile), { recursive: true });

  if (isWatch) {
    const context = await esbuild.context(buildOptions);
    await context.watch();
    console.log('Watching src/v2/sdk for changes...');
    return;
  }

  await esbuild.build(buildOptions);
  console.log(`Built ${outfile}`);
}

build().catch((error) => {
  console.error(error);
  process.exit(1);
});
